Add Fulfillment Service
getconversio/go-shopify pull request #115
Opened 2018-08-28 16:03 UTC by gir

Creating for @aryy this PR adds Fulfillment and helpers to Order.

2018-09-02 08:57 UTC, dlebech requested changes
Thanks for PR @gir There seems to be a few typos, but otherwise looks ok :-)

2018-09-02 08:57 UTC, dlebech commented on filfillment_test.go
> +package goshopify
There is a typo in the filename

2018-09-02 08:57 UTC, dlebech commented on fulfillment.go
> +	path := fmt.Sprintf("%s/%d.json", prefix, fulfillmentID)
I think this needs to be:
`path := fmt.Sprintf("%s/%d/complete.json", prefix, fulfillmentID)`

2018-09-02 08:57 UTC, dlebech commented on fulfillment.go
> +	path := fmt.Sprintf("%s/%d.json", prefix, fulfillmentID)
I think this needs to be:
`path := fmt.Sprintf("%s/%d/cancel.json", prefix, fulfillmentID)`

2018-09-02 08:57 UTC, dlebech commented on fulfillment.go
> +	path := fmt.Sprintf("%s/%d.json", prefix, fulfillmentID)
I think this needs to be:
`path := fmt.Sprintf("%s/%d/open.json", prefix, fulfillmentID)`

2018-09-07 17:37 UTC, andrewhoff commented
Hey @dlebech we're going to pull this in here, then make some changes on our fork

2018-09-07 17:59 UTC, dlebech approved these changes

2018-09-07 18:01 UTC, dlebech commented
@andrewhoff yeah no problem. Sorry for the wait. Feel free to merge when you're ready, the changes look good to me :-)

Thanks for the changes @gir 👍

2018-09-07 18:13 UTC, merged