Read variant
getconversio/go-shopify pull request #42
Opened 2017-10-16 18:51 UTC by sudomake

Added:

- Variant.List
- Variant.Count
- Variant.Get 

for the Read portion of #22

2017-10-17 10:01 UTC, dlebech requested changes
Thanks!

2017-10-17 10:01 UTC, dlebech commented on variant.go
> +// Count products
Small typo products -> variants

2017-10-18 07:46 UTC, stefanosala approved these changes

2017-10-18 08:33 UTC, dlebech approved these changes

2017-10-18 08:34 UTC, merged

2017-10-18 08:34 UTC, dlebech commented
Thanks @sudomake :trophy: