Support for customer.DefaultAddress, customer.Addresses
getconversio/go-shopify pull request #71
Opened 2018-03-20 17:45 UTC by seenickcode

At least when we fetch a customer, the addresses can be populated properly. 

Later, I plan to submit create/update capability.

2018-03-30 21:14 UTC, dlebech requested changes
Thanks for the PR @seenickcode :100: and sorry for the delay in responding here.

Looks like good additions. I only have two comments, and then I think this is good to go :beers:

2018-03-30 21:14 UTC, dlebech commented on checkout.go
> +	} `json:"tax_lines"`
Could you re-use the [`TaxLine`](https://github.com/getconversio/go-shopify/blob/9e3d52acdc5314e805f6399b908ec21413d68af3/order.go#L192-L196) struct here?

2018-03-30 21:14 UTC, dlebech commented on goshopify.go
> +				responseError.Errors = append(responseError.Errors, topicAndElem)
What is this part? It looks like this is the reason Codecov is complaining about coverage. Could you add a test that covers this use case?

2018-04-04 18:18 UTC, seenickcode commented
Hey thanks for the feedback. There'll be a delay in taking care of these due to some other blockers on another project I'm using this for.

2018-04-04 18:24 UTC, dlebech commented
@seenickcode thanks for getting back to me. Everything sounds good. No rush :-)

2018-09-07 18:20 UTC, andrewhoff commented
Hey @seenickcode we're going to close this PR. @rickywiens referenced it on the bold-commerce fork here https://github.com/bold-commerce/go-shopify/issues/3, where support for this project will continue. Feel free to open a PR there! Thanks!

2018-09-07 18:20 UTC, closed without merging