Add Metafield Resource
getconversio/go-shopify pull request #89
Opened 2018-05-31 00:39 UTC by aryy

* Adds the general Metafield resource (e.g. `client.Metafield.List(...)`)
* Adds metafields to Product resource (e.g. `client.Product.ListMetafields(...)`)

2018-06-02 18:33 UTC, dlebech requested changes
Thanks for the PR @aryy ! Looks very useful. I only have one comment on a piece of code that probably shouldn't be changed, and if you could fix the Travis error, that would be great. It's a small format problem in util_test and only seems to be a problem on Golang 1.10. The [error from Travis](https://travis-ci.org/getconversio/go-shopify/jobs/385965742):
```
./util_test.go:79: Errorf format %s has arg c.resourceID of wrong type int
```

2018-06-02 18:33 UTC, dlebech commented on goshopify.go
> +	}
Why did you make changes to this file? This seems to be unrelated to the main PR, so could you revert it for now?

2018-06-04 17:29 UTC, gir commented
Sorry, we'll point the PR at another branch and open another PR for the order-related changes as well.

2018-06-04 19:34 UTC, aryy commented
Closing in favor of https://github.com/getconversio/go-shopify/pull/90. This PR inadvertently pointed to our master branch.

2018-06-04 19:34 UTC, closed without merging